# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1265c5853694c9b172d91919a16d40ed0fac6374f7348467764aeea0c825ea00b29ae1773bf0dec01a1e900fc5117b2d4938a453906bcb737f56396d26ff6f0d

test:
  secret_key_base: 15cae34ffd78aa780df4e581c163c6afb7f603750325d47547465489e98c66efc35b7e7ad09380588d09b5ca41f554d8168662d95ea98d69737eb6b8c18f0b1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
